name: Work Stats Readme

on:
  workflow_dispatch:
  schedule:
      # Runs every 2 hours
      - cron: "00 01,13 * * *"

jobs:
  update-readme:
     name: Update this repo's README
     runs-on: ubuntu-latest
  steps:
    - uses: BhartiRathod/waka-readme@master
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
